Repository isaacgarza/spend-smart, pull requests merged in 2019-05, with the labels that each got.

#11 GH-6: moved SignUp.js to client/src/components
  client/src/components/SignUp.js
Labels: bug

#10 GH-4 added non functional sign in page
  client/src/App.js
  client/src/components/SignIn.js
  client/src/components/SignUp.js
Labels: feature

#15 GH-13: Created initial backend application using Spring Boot
  backend/.gitignore
  backend/.mvn/wrapper/MavenWrapperDownloader.java
  backend/.mvn/wrapper/maven-wrapper.jar
  backend/.mvn/wrapper/maven-wrapper.properties
  backend/mvnw
  backend/mvnw.cmd
  backend/pom.xml
  backend/src/main/java/com/spendsmart/SpendSmartBackendApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/spendsmart/SpendSmartBackendApplicationTests.java
Labels: backend, feature

#14 GH-9 Implemented Goals Component
  client/src/App.js
  client/src/components/Goals.css
  client/src/components/Goals.js
  client/src/components/Transactions.js
Labels: feature, goals

#19 GH-18: Updated the database DDL
  sql/ddl.sql
Labels: database, task

#20 GH-18: Updated the database DDL
  sql/ddl.sql
Labels: database, task

#28 GH-27: Added Expense Repeat Schedule Type Table
  sql/ddl.sql
  sql/dml/dml.sql
Labels: database, expenses
